package Presentacion.Interfaz_Usuario;

import Presentacion.Interfaz_Usuario.frmMenu_Usuario;
import Logica.Conexion;
import Logica.fLenguajes;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmViewLenguajes extends javax.swing.JFrame {

    public frmViewLenguajes() {
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.getContentPane().setBackground(Color.WHITE);
        
        LlenarTablaLenguajes();
    }

    private Conexion mysql = new Conexion();
    private Connection cn = mysql.Conectar();
    
   
    
    void LlenarTablaLenguajes(){
        
          try {
            DefaultTableModel modelo;
            fLenguajes func = new fLenguajes();

            modelo = func.mostrarLenguajes();

            tblLenguajes.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    
    
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLenguajes = new javax.swing.JTable();
        btnMenu1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMuniLeng = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lenguajes");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/File/hLenguajes.png"))); // NOI18N
        jLabel1.setToolTipText("");

        tblLenguajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLenguajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLenguajesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblLenguajes);

        btnMenu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/File/back.png"))); // NOI18N
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });

        tblMuniLeng.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMuniLeng);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed

        this.hide();
        frmMenu_Usuario menuUser = new frmMenu_Usuario();
        menuUser.show();
    }//GEN-LAST:event_btnMenu1ActionPerformed

    
   
    
    private void tblLenguajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLenguajesMouseClicked
        
   
        String nombre_lenguaje;
        int fila = tblLenguajes.rowAtPoint(evt.getPoint());

        nombre_lenguaje = tblLenguajes.getValueAt(fila, 0).toString();

        
        
          try {
            DefaultTableModel modelo;
            fLenguajes func = new fLenguajes();

            modelo = func.mostrarLenguajesMunicipios(nombre_lenguaje);

            tblMuniLeng.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    
        /*
        
        
        
        
    
        String nombre_lenguajes;
        int fila = tblLenguajes.rowAtPoint(evt.getPoint());

        nombre_lenguajes = tblLenguajes.getValueAt(fila, 0).toString();

        try {

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT municipios.nombre_municipio, regiones.nombre_region FROM municipios, regiones, lenguajes WHERE lenguajes.nombre_lengua = '" + nombre_lenguajes
                    + "' AND lenguajes.id_lengua = municipios_lenguajes.id_lengua AND municipios_lenguajes.id_municipio = municipios.id_municipio;");



            this.txtNomTrad.setText(rs.getString("nombre_tradicion"));
            this.txtDescTrad.setText(rs.getString("descripcion_tradicion"));
            this.txtFechaTrad.setText(rs.getString("fecha_festejo"));
            this.txtTipoTrad.setText(rs.getString("nombre_tipo_tradicion"));

            this.lblTradicionImagen.setIcon(ii);

        } catch (Exception e) {
            //ex.printStackTrace();
            //exx.printStackTrace();
        }


                                       
        
        
        */
    }//GEN-LAST:event_tblLenguajesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmViewLenguajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmViewLenguajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmViewLenguajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmViewLenguajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmViewLenguajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblLenguajes;
    private javax.swing.JTable tblMuniLeng;
    // End of variables declaration//GEN-END:variables
}
