package Presentacion.Administrador;

import Datos.dIntereses_Culturales;
import Datos.dTipoInteresCultural;
import Logica.Conexion;
import Logica.fInteresesCulturales;
import Logica.fMunicipios;
import Logica.fRegiones;
import Logica.fTipoInteresCultural;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alina
 */
public class frmAdmonIC extends javax.swing.JFrame {

    private Conexion mysql = new Conexion();
    private Connection cn = mysql.Conectar();

    private String accion = "agregar";

    String TipoIC;
    String CrearIdTipoTrad;

    String IdMunicipio;
    String IdRegion;

    int Condicion;

    boolean seInsertoImagen = false;
    public FileInputStream ImagenBinaria;

    public frmAdmonIC() {
        initComponents();

        llenandoComboBoxTipo();
        llenandoComboBoxRegion();
        llenandoComboBox_Municipios(IdRegion);

        mostrarDatos("", 1);

        this.setExtendedState(MAXIMIZED_BOTH);

    }

    void limpiarCampos() {

        this.txtNom.setText("");
        this.txtDes.setText("");
        this.txtId.setText("");
        this.txtHorario.setText("");
        this.txtImagenURL.setText("");
        this.lblImagen.setIcon(null);
        this.txtDir.setText("");
        
        TipoIC = "";

    }

    void mostrarDatos(String buscar, int tarea) {

        try {
            DefaultTableModel modelo;
            fInteresesCulturales func = new fInteresesCulturales();

            modelo = func.mostrarDatosCompletos(buscar, tarea);

            tblMostrar.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnHorario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtHorario = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnExaminar = new javax.swing.JButton();
        cobTipo = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTipoAgregar = new javax.swing.JTextField();
        btnAgregarTipo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnAgregarRegistros = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrar = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnBuscarId = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnMostrarTodo = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btnBuscarNombre = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDes = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        txtImagenURL = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnActualizarImagen = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        cobRegion = new javax.swing.JComboBox<>();
        cobMunicipio = new javax.swing.JComboBox<>();
        btnHorario1 = new javax.swing.JLabel();
        btnHorario2 = new javax.swing.JLabel();
        btnHorario3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDir = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1366, 768));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/File/hAdmonIC.jpg"))); // NOI18N

        jLabel2.setText("Identificador:");

        jLabel3.setText("Interes Cultural:");

        jLabel4.setText("Descripcion:");

        btnHorario.setText("Horario:");

        jLabel6.setText("Tipo:");

        lblImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen.setPreferredSize(new java.awt.Dimension(205, 128));

        jLabel15.setText("Imagen:");

        btnExaminar.setText("Examinar");
        btnExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarActionPerformed(evt);
            }
        });

        cobTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobTipoActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("¿Falta una tipo de interes cultural?"));

        jLabel18.setText("Agregue el tipo de interes cultural que necesite.");

        jLabel19.setText("Tipo:");

        btnAgregarTipo.setText("Agregar Tipo");
        btnAgregarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarTipo)))
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtTipoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarTipo)))
        );

        btnAgregarRegistros.setText("Agregar");
        btnAgregarRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRegistrosActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarRegistros)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificar)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarRegistros)
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMostrarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMostrar);

        btnBuscarId.setText("Identificador");
        btnBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnMostrarTodo.setText("Mostrar Todos");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });

        jLabel17.setText("Buscar:");

        btnBuscarNombre.setText("Nombre");
        btnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBuscarId)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(32, 32, 32)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(btnMostrarTodo)
                .addGap(68, 68, 68))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarTodo)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarId)
                    .addComponent(btnBuscarNombre)))
        );

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/File/back_menu.png"))); // NOI18N
        jButton10.setPreferredSize(new java.awt.Dimension(64, 64));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        txtDes.setColumns(20);
        txtDes.setRows(5);
        jScrollPane2.setViewportView(txtDes);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setText("Generar");

        btnActualizarImagen.setText("Actualizar Imagen");
        btnActualizarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarImagenActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Ubicacion"));

        cobRegion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cobRegionItemStateChanged(evt);
            }
        });
        cobRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobRegionActionPerformed(evt);
            }
        });

        cobMunicipio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cobMunicipioItemStateChanged(evt);
            }
        });
        cobMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobMunicipioActionPerformed(evt);
            }
        });

        btnHorario1.setText("Direccion:");

        btnHorario2.setText("Municipio:");

        btnHorario3.setText("Region:");

        txtDir.setColumns(20);
        txtDir.setRows(5);
        jScrollPane3.setViewportView(txtDir);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHorario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHorario3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cobMunicipio, 0, 155, Short.MAX_VALUE)
                            .addComponent(cobRegion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnHorario1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cobRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHorario3))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cobMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHorario2))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHorario1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtId)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1))
                                            .addComponent(jScrollPane2)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cobTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)))
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtImagenURL, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btnActualizarImagen))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHorario)
                            .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cobTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnExaminar)
                                    .addComponent(txtImagenURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizarImagen)
                        .addGap(38, 38, 38)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:

        mostrarDatos(txtBuscar.getText(), 1);
        this.txtId.setText(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarActionPerformed


    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        frmAdmonPrincipal frm = new frmAdmonPrincipal();
        frm.show();

        this.hide();
    }//GEN-LAST:event_jButton10ActionPerformed

    
    private void tblMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMostrarMouseClicked

        int fila = tblMostrar.rowAtPoint(evt.getPoint());

        //       fInteresesCulturales func = new fInteresesCulturales();
        //     dIntereses_Culturales dts = new dIntereses_Culturales();
        txtId.setText(tblMostrar.getValueAt(fila, 0).toString());
        txtNom.setText(tblMostrar.getValueAt(fila, 1).toString());
        txtDes.setText(tblMostrar.getValueAt(fila, 2).toString());
        txtHorario.setText(tblMostrar.getValueAt(fila, 3).toString());
        txtDir.setText(tblMostrar.getValueAt(fila, 4).toString());

        String tipo = tblMostrar.getValueAt(fila, 5).toString();
        String municipio = tblMostrar.getValueAt(fila, 6).toString();
        String region = tblMostrar.getValueAt(fila, 7).toString();

        cobTipo.setSelectedItem(tipo);
        cobMunicipio.setSelectedItem(municipio);
        cobRegion.setSelectedItem(region);
        
        try {

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT imagen_interes_cultural FROM intereses_culturales "
                                            + "WHERE id_interes_cultural = '" + txtId.getText() + "';");

            ImageIcon ii = null;
            InputStream is = null;
            rs.next();
            is = rs.getBinaryStream(1);
            BufferedImage bi = ImageIO.read(is);
            ii = new ImageIcon(bi.getScaledInstance(228, 128, 228));
            this.lblImagen.setIcon(ii);

        } catch (Exception e) {

        }

    }//GEN-LAST:event_tblMostrarMouseClicked

    void llenandoComboBoxTipo() {

        ArrayList<String> lista = new ArrayList<String>();

        fTipoInteresCultural func = new fTipoInteresCultural();
        lista = func.llenar_cob();

        for (int i = 0; i < lista.size(); i++) {
            cobTipo.addItem(lista.get(i));
        }

    }

    void llenandoComboBoxRegion() {

        ArrayList<String> lista = new ArrayList<String>();

        fRegiones func = new fRegiones();

        lista = func.llenar_combo_Regiones();

        for (int i = 0; i < lista.size(); i++) {
            cobRegion.addItem(lista.get(i));
        }

    }

    void llenandoComboBox_Municipios(String id) {

        ArrayList<String> lista = new ArrayList<String>();
        fMunicipios funcMunicipios = new fMunicipios();
        lista = funcMunicipios.llenar_combo_Municipios(id);

        for (int i = 0; i < lista.size(); i++) {
            cobMunicipio.addItem(lista.get(i));
        }
    }


    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        // TODO add your handling code here:

        mostrarDatos("", 1);

    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void btnBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdActionPerformed
        // TODO add your handling code here:
        mostrarDatos(txtBuscar.getText(), 1);
        Condicion = 1;


    }//GEN-LAST:event_btnBuscarIdActionPerformed

    private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed
        // TODO add your handling code here:

        mostrarDatos(txtBuscar.getText(), 2);
        Condicion = 2;

    }//GEN-LAST:event_btnBuscarNombreActionPerformed

    private void btnAgregarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTipoActionPerformed

        boolean band = true;
        
        CrearIdTipoTrad = txtTipoAgregar.getText().substring(0, 3);

        String IdTipoDefinitivo;

        IdTipoDefinitivo = CrearIdTipoTrad.toUpperCase() + "IC";

        if (txtTipoAgregar.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un dato");
            txtTipoAgregar.requestFocus();
            return;
        }

        if (!txtTipoAgregar.getText().equals("")) {

            fTipoInteresCultural f = new fTipoInteresCultural();

            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro que quieres ingresar el dato?", "Confirmar", 2);

            if (confirmacion == 0) {

                String dato;

                dTipoInteresCultural dts = new dTipoInteresCultural();
                fTipoInteresCultural func = new fTipoInteresCultural();

                dts.setId_Tipo_Interes_Cult(IdTipoDefinitivo);
                dts.setNombre_Tipo_Interes_Cult(txtTipoAgregar.getText());

                func.insertar(dts);

                JOptionPane.showConfirmDialog(rootPane, "Dato Ingresado con un Id: " + IdTipoDefinitivo + "");

                llenandoComboBoxTipo();

            }

        }


    }//GEN-LAST:event_btnAgregarTipoActionPerformed

    private void btnExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarActionPerformed

        try {

            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de Imagenes", "jpg", "jpeg", "png");

            JFileChooser archivo = new JFileChooser();
            archivo.setDialogTitle("Abrir Imagen...");

            archivo.addChoosableFileFilter(filtro);

            File ruta = new File("C:\\Users\\alina\\Pictures\\");

            archivo.setCurrentDirectory(ruta);

            int ventana = archivo.showOpenDialog(null);

            if (ventana == JFileChooser.APPROVE_OPTION) {

                File file = archivo.getSelectedFile();
                txtImagenURL.setText(String.valueOf(file));
                Image foto = getToolkit().getImage(txtImagenURL.getText());
                ImageIcon ic = new ImageIcon();
                foto = foto.getScaledInstance(360, 180, Image.SCALE_DEFAULT);

                ImagenBinaria = new FileInputStream(txtImagenURL.getText());


                ic = new ImageIcon(foto.getScaledInstance(228, 128, 228));

                lblImagen.setIcon(ic);

                seInsertoImagen = true;

            }

        } catch (Exception e) {

        }


    }//GEN-LAST:event_btnExaminarActionPerformed

    private void btnAgregarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRegistrosActionPerformed

        accion = "agregar";

        if (txtId.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un identificador");
            txtId.requestFocus();
            return;
        }

        if (txtNom.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un nombre");
            txtNom.requestFocus();
            return;
        }

        if (txtDes.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una descripcion");
            txtDes.requestFocus();
            return;
        }

        if (txtHorario.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un horario");
            txtHorario.requestFocus();
            return;
        }

        if (seInsertoImagen == false) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una imagen");
            btnExaminar.requestFocus();
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro de agregar el registro?", "Confirmar", 2);

        if (confirmacion == 0) {

            dIntereses_Culturales dts = new dIntereses_Culturales();
            fInteresesCulturales func = new fInteresesCulturales();

            dts.setId_Interes_Cultural(txtId.getText());
            dts.setDescripcion_Interes_Cultural(txtDes.getText());
            dts.setNombre_Interes_Cultural(txtNom.getText());
            dts.setHorario_Interes_Cultural(txtHorario.getText());
            dts.setDireccion_Interes_Cultural(txtDir.getText());
            dts.setImagen_Interes_Cultural(ImagenBinaria);
            dts.setId_Tipo_Interes(TipoIC);
            dts.setId_Municipio(IdMunicipio);

            func.insertar(dts);

            mostrarDatos("", 1);
            limpiarCampos();

            JOptionPane.showConfirmDialog(rootPane, "Dato Ingresado correctamente...");
            seInsertoImagen = false;

        }


    }//GEN-LAST:event_btnAgregarRegistrosActionPerformed

    private void cobTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobTipoActionPerformed
        // TODO add your handling code here:

        try {

            //    Limpiar();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM tipo_intereses_culturales WHERE nombre_tipo_interes = '"
                    + this.cobTipo.getSelectedItem() + "';");

            rs.next();

            TipoIC = rs.getString("id_tipo_interes");

            //       llenandoComboBox_Municipios(IdRegion);
        } catch (Exception e) {

        }


    }//GEN-LAST:event_cobTipoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        if (!txtId.getText().equals("")) {

            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro de eliminar el registro?", "Confirmar", 2);

            if (confirmacion == 0) {
                fInteresesCulturales func = new fInteresesCulturales();
                dIntereses_Culturales dts = new dIntereses_Culturales();

                dts.setId_Interes_Cultural(txtId.getText());

                func.eliminar(dts);

                mostrarDatos("", 1);
                limpiarCampos();
                JOptionPane.showConfirmDialog(rootPane, "Dato Eliminado...");

            }

        }


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:

        if (!txtId.getText().equals("")) {

            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro de modificar el registro?", "Confirmar", 2);

            if (confirmacion == 0) {

                fInteresesCulturales func = new fInteresesCulturales();
                dIntereses_Culturales dts = new dIntereses_Culturales();

                
            dts.setId_Interes_Cultural(txtId.getText());
            dts.setDescripcion_Interes_Cultural(txtDes.getText());
            dts.setNombre_Interes_Cultural(txtNom.getText());
            dts.setHorario_Interes_Cultural(txtHorario.getText());
            dts.setDireccion_Interes_Cultural(txtDir.getText());
            dts.setImagen_Interes_Cultural(ImagenBinaria);
            dts.setId_Tipo_Interes(TipoIC);
            dts.setId_Municipio(IdMunicipio);

                func.modificar(dts);
                mostrarDatos("", 1);

                if (func.modificar(dts)) {
                    JOptionPane.showConfirmDialog(rootPane, "Los datos se modificaron correctamente");

                    this.txtImagenURL.setText("");
                    limpiarCampos();

                }

            }

        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnActualizarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarImagenActionPerformed
        // TODO add your handling code here:

        if (!txtId.getText().equals("")) {

            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro de actualizar la imagen?", "Confirmar", 2);

            if (confirmacion == 0) {

                fInteresesCulturales func = new fInteresesCulturales();
                dIntereses_Culturales dts = new dIntereses_Culturales();

                dts.setId_Interes_Cultural(txtId.getText());
                dts.setImagen_Interes_Cultural(ImagenBinaria);

                func.actualizarImagen(dts);
                mostrarDatos("", 1);

                if (func.modificar(dts)) {
                    JOptionPane.showConfirmDialog(rootPane, "La imagen se actualizo correctamente");
                    this.txtImagenURL.setText("");
                    limpiarCampos();
                    seInsertoImagen = false;

                }

            }

        }

    }//GEN-LAST:event_btnActualizarImagenActionPerformed

    private void cobRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobRegionActionPerformed
        // TODO add your handling code here:

        try {

            //Limpiar();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM regiones WHERE nombre_region = '"
                    + this.cobRegion.getSelectedItem() + "';");

            rs.next();

            IdRegion = rs.getString("id_region");

            llenandoComboBox_Municipios(IdRegion);

        } catch (Exception e) {

        }


    }//GEN-LAST:event_cobRegionActionPerformed

    private void cobMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobMunicipioActionPerformed
        // TODO add your handling code here:

        try {

            //Limpiar();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM municipios WHERE nombre_municipio = '"
                    + this.cobMunicipio.getSelectedItem() + "';");

            rs.next();

            IdMunicipio = rs.getString("id_municipio");

            // llenandoComboBox_Municipios(IdRegion);
        } catch (Exception e) {

        }

    }//GEN-LAST:event_cobMunicipioActionPerformed

    private void cobRegionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cobRegionItemStateChanged
        // TODO add your handling code here:

        if (evt.getStateChange() == ItemEvent.SELECTED) {

            this.cobMunicipio.setModel(new DefaultComboBoxModel());

        }

    }//GEN-LAST:event_cobRegionItemStateChanged

    private void cobMunicipioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cobMunicipioItemStateChanged
        // TODO add your handling code here:
        
        
        try {

            //Limpiar();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM municipios WHERE nombre_municipio = '"
                    + this.cobRegion.getSelectedItem() + "';");

            rs.next();

            IdMunicipio = rs.getString("id_municipio");

            // llenandoComboBox_Municipios(IdRegion);
        } catch (Exception e) {

        }

       
    }//GEN-LAST:event_cobMunicipioItemStateChanged
    /**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdmonIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdmonIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdmonIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdmonIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdmonIC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarImagen;
    private javax.swing.JButton btnAgregarRegistros;
    private javax.swing.JButton btnAgregarTipo;
    private javax.swing.JButton btnBuscarId;
    private javax.swing.JButton btnBuscarNombre;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExaminar;
    private javax.swing.JLabel btnHorario;
    private javax.swing.JLabel btnHorario1;
    private javax.swing.JLabel btnHorario2;
    private javax.swing.JLabel btnHorario3;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JComboBox<String> cobMunicipio;
    private javax.swing.JComboBox<String> cobRegion;
    private javax.swing.JComboBox<String> cobTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTable tblMostrar;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtDes;
    private javax.swing.JTextArea txtDir;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtImagenURL;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtTipoAgregar;
    // End of variables declaration//GEN-END:variables
}
